### ISSUE TITLE
Invalid SBML generated

### ISSUE THREAD

**Issue by murti-abhishek** [varnerlab/CFMG#12]
The SBML file generated using `make_sbml_model` is not valid SBML.

Valid SBML files can be checked using the inbuilt cobra function : `cobra.io.sbml.validate_sbml_model(path_to_SBML_file)`

**Comment by varnerlab** [comment]
I don't have access to MATALB - does this test require MATLAB? If so, then I can't use it.

**Comment by varnerlab** [comment]
Just generated test SBML file, and checked with libSBML via PyCall. Generated file can be parsed by libSBML. Procedure can be found here: https://stochasticreveller.wordpress.com/2016/08/02/sbml-and-the-julia-programming-language/

**Comment by ZZP12** [comment]
I could open the generated SBML with PyCall in Julia1.5
