### ISSUE TITLE
documentation with Documenter.jl 

### ISSUE THREAD

**Issue by ZZP12** [varnerlab/CFMG#15]
I updated the repository for generating documentation with `Documenter.jl` as we discussed. 
I think the documentation has already been generated.

But the documentation has to be published as a GitHub page for it to be available online.
[![](https://img.shields.io/badge/docs-stable-blue.svg)](https://varnerlab.github.io/CFMG/stable)
And only the owner has the capability to do it by following [Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) and choosing `Branch: gh-pages` as  the source of the GitHub Pages site in CFMG repository settings `GitHub Pages`, so that GitHub would actually serve the contents as a website.

For `testseml.jl`, it is 
[![](https://img.shields.io/badge/docs-stable-blue.svg)](https://zzp12.github.io/testseml/stable)

**Comment by varnerlab** [comment]
I'll take care of this - now
